### ISSUE TITLE
Action scaling for humanoid muscle

### ISSUE THREAD

**Issue by OliEfr** [robfiras/loco-mujoco#43]
For [humanoid muscle](https://loco-mujoco.readthedocs.io/en/latest/source/humanoids/muscle_humanoid.html) it says default action space is in `[-1, 1]`. When I use the replay script that I PRed earlier #41 (which works fine) and look at the actions of the `perfect` dataset, I see that the actions are _roughly_ in `[-2,2]` (just an estimate from looking at the actions). So what actions exactly am I looking at? How should I setup the action space, if I want to do RL training with the env?

Here is an example of `np.min(expert_actions_sample)` and `np.max(expert_actions_sample)`: `[-2.1862778663635254, 2.0014350414276123]`

When I do `env.action_space` I get `Box(-1.0, 1.0, (92,), float64)`.

**Comment by robfiras** [comment]
Hi,
The action space in LocoMuJoCo is always in [-1, 1]. Any actions outside this interval will be clipped internally by Mujoco. The expert actions are currently sampled from a policy trained with one of our baselines. It could be that samples are outside the interval (nothing enforces the policy to be inbound), but they will be clipped. 
This was mentioned in #33. 
We might clipp the expert actions in the dataset in the future.
