### ISSUE TITLE
Clarification Request on Dataset Dimensions for Unitree G1

### ISSUE THREAD

**Issue by XinyuSong123** [robfiras/loco-mujoco#48]
Hi, I am planning to use the motion dataset for the Unitree G1. However, I couldn't find any details in the documentation regarding which dimensions of the dataset correspond to specific joints. Could you please provide more detailed information about the dataset? Thank you for your assistance!

**Comment by mertalbaba** [comment]
Hey Xinyu, did you find it? I also need it.
