### ISSUE TITLE
How do you get the ground truth expert data for humanoid robots?

### ISSUE THREAD

**Issue by wenshuaizhao** [robfiras/loco-mujoco#7]
Hi,

Interesting work! But I didn't get the information from the paper, how do you get the ground truth data with actions for humanoid robots, such as Atlas?

Thanks

**Comment by robfiras** [comment]
We optimize the motion capture towards a base humanoid model using Qualsys' optimization software (see paper for reference). Then we manually adapt this data to the different humanoid embodiment using affine transformations. To get the actions, we use the baseline algorithms provided to learn a policy that imitates the motion capture data as good as possible. We will provide the experimental setup, such that you can train an agent yourself if you want.

**Comment by wenshuaizhao** [comment]
Thanks for your detailed explanation!
