### ISSUE TITLE
How to resume last training

### ISSUE THREAD

**Issue by craipy-hub** [robfiras/loco-mujoco#9]
I am using the example to train the "Atlas.walk",but i dont know how to resume the training.
I can only start training from scratch every time, which is very inefficient

**Comment by robfiras** [comment]
Hi!
you can save agents with

```python
path = "your_path"
agent.save(path, full=True)
```

The full save is needed to store also the expert dataset, which is needed if you want to resume training. For inference only, that wouldn't be needed. Note that the `BestAgentSaver` already saves the best agents in the interval `n_epochs_save` specified in the launcher file.

You can load an agent with:
```python
from mushroom_rl.core import Agent
path = "your_path"
agent  = Agent.load(path)
```

I also just found a bug during saving in the imitation learning repo (ls-iq), please pull the latest changes before trying it out. 
The only thing that is currently not working after loading an agent is the tensorboard logger (it is causing a pickle error during saving). So you have to log information on your own.

Let me know if there is anything else!

Best,
Firas
